### ISSUE TITLE
Multiple ignored strings

### ISSUE THREAD

**Issue by aliakseiz** [jgautheron/goconst#26]
Would be nice if this linter supported multiple strings to ignore.

```yaml
  goconst:
    # Exclude strings matching the given regular expressions.
    # Default: ""
    ignore-strings: 
      - 'foo.+'
      - 'baa.+'
```

Relates to https://github.com/jgautheron/goconst/issues/22
