### ISSUE TITLE
`ignore-tests` option does not ignore test files

### ISSUE THREAD

**Issue by PSalant726** [jgautheron/goconst#5]
As stated in the `README`:
> ``` -ignore-tests      exclude tests from the search (default: true) ```

However, when using this linter as part of `golangci-lint`, I am met with errors in `*_test.go` files that live adjacent to their companion `*.go` file in the directory.

I still notice this issue when adding the following to my `.golangci.yml` config:
```yaml
linters-settings:
  goconst:
    ignore-tests: true
```
